// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: internal/proto/publisher.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PublisherServiceClient is the client API for PublisherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublisherServiceClient interface {
	CreatePublisher(ctx context.Context, in *PublisherCreateRequest, opts ...grpc.CallOption) (*PublisherCreateResponse, error)
	FetchByIdPublisher(ctx context.Context, in *PublisherFetchByIdRequest, opts ...grpc.CallOption) (*PublisherFetchByIdResponse, error)
	FetchByNamePublisher(ctx context.Context, in *PublisherFetchByNameRequest, opts ...grpc.CallOption) (*PublisherFetchByNameResponse, error)
	FetchAllPublisher(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublisherFetchAllResponse, error)
	UpdatePublisher(ctx context.Context, in *PublisherUpdateRequest, opts ...grpc.CallOption) (*PublisherUpdateResponse, error)
	DeletePublisher(ctx context.Context, in *PublisherDeleteRequest, opts ...grpc.CallOption) (*PublisherDeleteResponse, error)
}

type publisherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublisherServiceClient(cc grpc.ClientConnInterface) PublisherServiceClient {
	return &publisherServiceClient{cc}
}

func (c *publisherServiceClient) CreatePublisher(ctx context.Context, in *PublisherCreateRequest, opts ...grpc.CallOption) (*PublisherCreateResponse, error) {
	out := new(PublisherCreateResponse)
	err := c.cc.Invoke(ctx, "/publisher.PublisherService/CreatePublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) FetchByIdPublisher(ctx context.Context, in *PublisherFetchByIdRequest, opts ...grpc.CallOption) (*PublisherFetchByIdResponse, error) {
	out := new(PublisherFetchByIdResponse)
	err := c.cc.Invoke(ctx, "/publisher.PublisherService/FetchByIdPublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) FetchByNamePublisher(ctx context.Context, in *PublisherFetchByNameRequest, opts ...grpc.CallOption) (*PublisherFetchByNameResponse, error) {
	out := new(PublisherFetchByNameResponse)
	err := c.cc.Invoke(ctx, "/publisher.PublisherService/FetchByNamePublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) FetchAllPublisher(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublisherFetchAllResponse, error) {
	out := new(PublisherFetchAllResponse)
	err := c.cc.Invoke(ctx, "/publisher.PublisherService/FetchAllPublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) UpdatePublisher(ctx context.Context, in *PublisherUpdateRequest, opts ...grpc.CallOption) (*PublisherUpdateResponse, error) {
	out := new(PublisherUpdateResponse)
	err := c.cc.Invoke(ctx, "/publisher.PublisherService/UpdatePublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) DeletePublisher(ctx context.Context, in *PublisherDeleteRequest, opts ...grpc.CallOption) (*PublisherDeleteResponse, error) {
	out := new(PublisherDeleteResponse)
	err := c.cc.Invoke(ctx, "/publisher.PublisherService/DeletePublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherServiceServer is the server API for PublisherService service.
// All implementations must embed UnimplementedPublisherServiceServer
// for forward compatibility
type PublisherServiceServer interface {
	CreatePublisher(context.Context, *PublisherCreateRequest) (*PublisherCreateResponse, error)
	FetchByIdPublisher(context.Context, *PublisherFetchByIdRequest) (*PublisherFetchByIdResponse, error)
	FetchByNamePublisher(context.Context, *PublisherFetchByNameRequest) (*PublisherFetchByNameResponse, error)
	FetchAllPublisher(context.Context, *emptypb.Empty) (*PublisherFetchAllResponse, error)
	UpdatePublisher(context.Context, *PublisherUpdateRequest) (*PublisherUpdateResponse, error)
	DeletePublisher(context.Context, *PublisherDeleteRequest) (*PublisherDeleteResponse, error)
	mustEmbedUnimplementedPublisherServiceServer()
}

// UnimplementedPublisherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublisherServiceServer struct {
}

func (UnimplementedPublisherServiceServer) CreatePublisher(context.Context, *PublisherCreateRequest) (*PublisherCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePublisher not implemented")
}
func (UnimplementedPublisherServiceServer) FetchByIdPublisher(context.Context, *PublisherFetchByIdRequest) (*PublisherFetchByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchByIdPublisher not implemented")
}
func (UnimplementedPublisherServiceServer) FetchByNamePublisher(context.Context, *PublisherFetchByNameRequest) (*PublisherFetchByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchByNamePublisher not implemented")
}
func (UnimplementedPublisherServiceServer) FetchAllPublisher(context.Context, *emptypb.Empty) (*PublisherFetchAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAllPublisher not implemented")
}
func (UnimplementedPublisherServiceServer) UpdatePublisher(context.Context, *PublisherUpdateRequest) (*PublisherUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePublisher not implemented")
}
func (UnimplementedPublisherServiceServer) DeletePublisher(context.Context, *PublisherDeleteRequest) (*PublisherDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePublisher not implemented")
}
func (UnimplementedPublisherServiceServer) mustEmbedUnimplementedPublisherServiceServer() {}

// UnsafePublisherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublisherServiceServer will
// result in compilation errors.
type UnsafePublisherServiceServer interface {
	mustEmbedUnimplementedPublisherServiceServer()
}

func RegisterPublisherServiceServer(s grpc.ServiceRegistrar, srv PublisherServiceServer) {
	s.RegisterService(&PublisherService_ServiceDesc, srv)
}

func _PublisherService_CreatePublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublisherCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).CreatePublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.PublisherService/CreatePublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).CreatePublisher(ctx, req.(*PublisherCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_FetchByIdPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublisherFetchByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).FetchByIdPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.PublisherService/FetchByIdPublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).FetchByIdPublisher(ctx, req.(*PublisherFetchByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_FetchByNamePublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublisherFetchByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).FetchByNamePublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.PublisherService/FetchByNamePublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).FetchByNamePublisher(ctx, req.(*PublisherFetchByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_FetchAllPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).FetchAllPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.PublisherService/FetchAllPublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).FetchAllPublisher(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_UpdatePublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublisherUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).UpdatePublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.PublisherService/UpdatePublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).UpdatePublisher(ctx, req.(*PublisherUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_DeletePublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublisherDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).DeletePublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.PublisherService/DeletePublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).DeletePublisher(ctx, req.(*PublisherDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublisherService_ServiceDesc is the grpc.ServiceDesc for PublisherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublisherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "publisher.PublisherService",
	HandlerType: (*PublisherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePublisher",
			Handler:    _PublisherService_CreatePublisher_Handler,
		},
		{
			MethodName: "FetchByIdPublisher",
			Handler:    _PublisherService_FetchByIdPublisher_Handler,
		},
		{
			MethodName: "FetchByNamePublisher",
			Handler:    _PublisherService_FetchByNamePublisher_Handler,
		},
		{
			MethodName: "FetchAllPublisher",
			Handler:    _PublisherService_FetchAllPublisher_Handler,
		},
		{
			MethodName: "UpdatePublisher",
			Handler:    _PublisherService_UpdatePublisher_Handler,
		},
		{
			MethodName: "DeletePublisher",
			Handler:    _PublisherService_DeletePublisher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/publisher.proto",
}
