// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fahmyabdul/gits-assignments/test-3/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// UsecasePublisher is an autogenerated mock type for the UsecasePublisher type
type UsecasePublisher struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *UsecasePublisher) Create(ctx context.Context, request *entity.Publisher) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Publisher) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UsecasePublisher) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAll provides a mock function with given fields: ctx
func (_m *UsecasePublisher) FetchAll(ctx context.Context) ([]*entity.Publisher, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Publisher
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Publisher); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Publisher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchById provides a mock function with given fields: ctx, id
func (_m *UsecasePublisher) FetchById(ctx context.Context, id int) (*entity.Publisher, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Publisher
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Publisher); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Publisher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByName provides a mock function with given fields: ctx, name
func (_m *UsecasePublisher) FetchByName(ctx context.Context, name string) ([]*entity.Publisher, error) {
	ret := _m.Called(ctx, name)

	var r0 []*entity.Publisher
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Publisher); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Publisher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, request
func (_m *UsecasePublisher) Update(ctx context.Context, id int, request *entity.Publisher) error {
	ret := _m.Called(ctx, id, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *entity.Publisher) error); ok {
		r0 = rf(ctx, id, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsecasePublisher interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecasePublisher creates a new instance of UsecasePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecasePublisher(t mockConstructorTestingTNewUsecasePublisher) *UsecasePublisher {
	mock := &UsecasePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
