stages:
  - deployments

deployment_dev:
  stage: deployments
  trigger:
    include: deployments/ci/.gitlab-ci.dev.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'

deployment_prod:
  stage: deployments
  trigger:
    include: deployments/ci/.gitlab-ci.prod.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == 'production'
